### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by bnmajor**
1. Fix the image links in the README so that they will also work for PyPi documentation
2. Update the Spleen Segmentation screenshots. Instead of showing the output model alone, add the input label so that you can see the difference between the input and output model.
3. Re-organize the images into appropriate sub-directories for the docs and notebooks.
4. Add some example images to the docs as well

### CODE REVIEW

**Review by thewtex — DISMISSED** [review]
Nice, love the GIF's! :smile_cat:

**Review by thewtex — CHANGES_REQUESTED** [review]
>  +30.3 MB docs/images/label_with_output.gif 

@bnmajor for the gif's, could you please run them through https://ezgif.com/optimize then rebase, add, force push? This will keep our Git repository size down and enable them to be loaded quickly in the documentation.

**Comment by bnmajor** [comment]
@thewtex Of course, that makes sense. I've compressed `label_with_output.gif` and it has gone from ~30 MB to ~9MB. I did not compress `unet.gif` as it is ~2MB. Let me know if these seem more appropriately sized now, thanks!

**Comment by thewtex** [comment]
@bnmajor thanks!

**Review by thewtex — APPROVED** [review]

**Pull request merged**
